authentication/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'authentication'

urlpatterns = [
     path(
        route='profile/<int:pk>/',
        view=views.UserDetail.as_view(),
        name='member_profile'
    ),
    path(
        route='update/<int:pk>/',
        view=views.UserUpdateView.as_view(),
        name='user_update'
    ),
    # Login and Password reset
    path(
        route='signup/',
        view=views.UserRegisterView.as_view(),
        name='signup'
    ),
    path(route='signup/successful', view=views.SignUpSuccessful.as_view(), name='signup_successful'),
    path(
        route='login/',
        view=views.UserLoginView.as_view(),
        name='login'
    ),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    path(
        route='reset-password',
        view=views.PasswordResetView.as_view(),
        name='password_reset'
    ),
    path('password-reset/done/', views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/',
         views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset_complete/done/', views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
    path('password-change', views.PasswordChangeView.as_view(),
         name='password_change'),
    path('password-change/done/', views.PasswordChangeDoneView.as_view(),
         name='password_change_done'),
     path('email/verification/confirm', views.EmailVerificationConfirm.as_view(),
         name='email_verification_confirm'),
     path('email/verification/invalid', views.EmailVerificationInvalid.as_view(),
         name='email_verification_invalid'),
    path('activate/<uidb64>/<token>/',
         views.activate, name='activate'),

]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.ShopView.as_view(), name='home'),
    path('shop/<str:slug>/', views.CategoryProductView.as_view(), name='category'),
    path('check-out/', views.CheckOut.as_view() , name='checkout'),
    path('user-account/', views.UserAccountView.as_view() , name='account'),

    path('config/', views.stripe_config),
    path('success/', views.SuccessView.as_view()),
    path('cancel/', views.CancelledView.as_view()),
    path(
        route='search_results',
        view=views.SearchResultsList.as_view(),
        name='search_results'
    ),
]

authentication/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractUser
from wagtail.snippets.models import register_snippet
from wagtail.admin.panels import FieldPanel, InlinePanel, FieldRowPanel, MultiFieldPanel, PageChooserPanel
from django.utils.translation import gettext_lazy as _
from django.utils.text import slugify
from django.urls import reverse
from cloudinary.models import CloudinaryField
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser, PermissionsMixin

class MyUserManager(BaseUserManager):
    def create_user(self, email, password=None):
        """
        Creates and saves a User with the given email and password.
        """
        if not email:
            raise ValueError("Users must have an email address")

        user = self.model(
            email=self.normalize_email(email),
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(
            email,
            password=password,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user
class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(verbose_name='email', max_length=255, unique=True)
    first_name = models.CharField(verbose_name='First Name', max_length=255, null=True, blank=True)
    last_name = models.CharField(verbose_name='Last Name', max_length=255, null=True, blank=True)
    date_joined = models.DateTimeField(verbose_name='date joined', auto_now_add=True, null=True)
    last_login = models.DateTimeField(verbose_name='last login', auto_now=True, null=True)
    country = models.CharField(verbose_name='country', max_length=255, null=True, blank=True)
    region = models.CharField(verbose_name='region', max_length=255, null=True, blank=True)
    city = models.CharField(verbose_name='country', max_length=255, null=True, blank=True)
    phone_number = models.CharField(max_length=255, null=True, blank=True)
    residential_address = models.CharField(max_length=255, null=True, blank=True)
    avatar = CloudinaryField("image", null=True, blank=True)

    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    # is_staff = models.BooleanField(default=False)

    objects = MyUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def get_absolute_url(self):
        return reverse('shop:account')
    
    @property
    def full_name(self):
        return f'{self.first_name} {self.last_name}'

    def __str__(self):
        return f'{self.email} - {self.full_name}'

authentication/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from wagtail.users.forms import UserEditForm, UserCreationForm

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.utils.translation import gettext_lazy as _
# from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import (
    AuthenticationForm,
)
from authentication.models import User


class UserSignInForm(AuthenticationForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder': 'Email'}), label='Email')
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Password..'}), label='Password')

    class Meta:
        model = User
        fields = ['email', 'password']
class UserRegisterForm(UserCreationForm):
    """
        Creates User registration form for signing up.
    """
    def __init__(self, *args, **kwargs):
        super(UserRegisterForm, self).__init__(*args, **kwargs)
        # self.fields['username'].widget.attrs.pop("autofocus", None)

    email = forms.EmailField(max_length=254, required=True, widget=forms.EmailInput(attrs={
        "name": "email", "class": "input100",
        "placeholder": "Email"
    }
    ),
        help_text='Required. Input a valid email address.'
    )
    password1 = forms.CharField(label="Password",
    widget=forms.PasswordInput(attrs={
        "name": "password", "class": "input100",
        "placeholder": "Password"
    }
    ),
    )

    password2 = forms.CharField(label="Confirm Password",
                                help_text=_(
                                    "Enter the same password as before, for verification."),
    widget=forms.PasswordInput(attrs={"name": "Confirm Password", "class": "input100", "placeholder": "Confirm Password"}),
    )

    class Meta:
        model = User
        fields = ['email', 'password1', 'password2']
        # widgets = {

        #     "username": forms.TextInput(attrs={
        #         "name": "username", "class": "input100",
        #         "placeholder": "Username"
        #     }),
        # }

    def save(self, commit=True):
        user = super(UserRegisterForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user
    
class CustomUserEditForm(UserEditForm):
    email = forms.CharField(required=False, label=_("Email"))
    country = forms.CharField(required=False, label=_("Country"))
    region = forms.CharField(required=False, label=_("State"))
    city = forms.CharField(required=False, label=_("City"))
    phone_number = forms.CharField(required=False, label=_("Phone number"))
    residential_address = forms.CharField(required=False, label=_("Residential address"))
    avatar = forms.ImageField(required=False, label=_("Avatar"))


class CustomUserCreationForm(UserCreationForm):
    email = forms.CharField(required=False, label=_("Email"))
    country = forms.CharField(required=False, label=_("Country"))
    region = forms.CharField(required=False, label=_("State"))
    city = forms.CharField(required=False, label=_("City"))
    phone_number = forms.CharField(required=False, label=_("Phone number"))
    residential_address = forms.CharField(required=False, label=_("Residential address"))
    avatar = forms.ImageField(required=False, label=_("Avatar"))

authentication/views.py
from django.shortcuts import render
from django.contrib.auth.forms import (
    AuthenticationForm,
)
from django.urls import reverse_lazy
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import TemplateView, DetailView
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic import View
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.contrib.auth.tokens import default_token_generator
from django.utils.http import urlsafe_base64_decode
from django.urls import reverse_lazy, reverse
from django.contrib.auth import get_user_model
User = get_user_model()
from django.contrib.auth.views import (PasswordResetDoneView, PasswordResetConfirmView,
                                        PasswordResetCompleteView, PasswordChangeView,
                                       PasswordChangeDoneView, PasswordResetView)
from .models import User as Member
from django.http.response import HttpResponseRedirect
from django.core.mail import EmailMessage
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes
from django.contrib.sites.shortcuts import get_current_site
from .forms import UserRegisterForm
from django.contrib.auth.mixins import LoginRequiredMixin
from authentication.forms import UserSignInForm
from wagtail.admin.forms.auth import LoginForm
# Create your views here.

class SignUpSuccessful(TemplateView):
    template_name = 'authentication/thanks.html'
class UserDetail(LoginRequiredMixin, DetailView):
    model = Member
    template_name = 'courses/profile_detail.html'
    login_url = "authentication:login"
    redirect_field_name = "redirect_to"

class UserUpdateView(LoginRequiredMixin, UpdateView):
    fields = ['first_name', 'last_name', 'email', 'country', 'region', 'city', 'phone_number', 'residential_address', 'avatar']
    model = Member
    template_name = 'authentication/user_update.html'
    login_url = "authentication:login"
    redirect_field_name = "redirect_to"
class UserLoginView(View):
    """
     Logs author into dashboard.
    """
    template_name = 'authentication/login.html'
    context_object = {"login_form": LoginForm}

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, self.context_object)

    def post(self, request, *args, **kwargs):

        login_form = LoginForm(data = request.POST)

        if login_form.is_valid():
            email = login_form.cleaned_data['username']
            password = login_form.cleaned_data['password']
            user = authenticate(request, email=email, password=password)

            
            login(request, user)
            messages.success(request, f"Login Successful ! "
                                f"Welcome {user.email}.")
            
            return redirect('shop:home')

        else:
            messages.error(request,
                           f"Please enter a correct email and password. Note that both fields may be case-sensitive."
                           )
            return render(request, self.template_name, self.context_object)

class UserRegisterView(View):
    """
      View to let users register
    """
    template_name = 'authentication/register.html'
    context = {
        "register_form": UserRegisterForm()
    }

    def get(self, request):
        success_message = "Successful"

        self.context['success_message'] = success_message
        return render(request, self.template_name, self.context)

    def post(self, request, *args, **kwargs):

        register_form = UserRegisterForm(request.POST)

        if register_form.is_valid():
            user = register_form.save(commit=False)
            user.is_active = True
            user.is_staff = True
            user.save()
            current_site = get_current_site(request)
            mail_subject = 'Activate your account.'
            message = render_to_string('authentication/activate_email.html'
                                       , {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': default_token_generator.make_token(user),
                'protocol': 'https',
            }
            )
            from_email = 'tabitha.market@gmail.com'
            to_email = register_form.cleaned_data.get('email')
            email = EmailMessage(
                mail_subject, message, from_email, to=[to_email]
            )
            email.send()

            return HttpResponseRedirect(reverse_lazy('authentication:email_verification_confirm'))

        else:
            messages.error(request, "Please provide valid information.")
            # Redirect user to register page
            return render(request, self.template_name, self.context)

    # def get_success_url(self):
    #     return reverse('authentication:signup_successful')


class PasswordResetView(PasswordResetView):
    template_name = 'authentication/pwd_reset_form.html'
    email_template_name = "authentication/email_text/password_reset_email.html"
    from_email = ''
    subject_template_name = "authentication/email_text/password_reset_subject.txt"
    success_url = reverse_lazy("authentication:password_reset_done")

class PasswordResetDoneView(PasswordResetDoneView):
    template_name = 'authentication/email_text/password_reset_done.html' 

class PasswordResetConfirmView(PasswordResetConfirmView):
    template_name = 'authentication/email_text/password_reset_confirm.html'
    success_url = reverse_lazy("authentication:password_reset_complete")

class PasswordResetCompleteView(PasswordResetCompleteView):
    template_name = 'authentication/email_text/password_reset_complete.html'

class PasswordChangeView(PasswordChangeView):
    template_name = 'authentication/email_text/password_change_form.html'
    success_url = reverse_lazy("authentication:password_change_done")

class PasswordChangeDoneView(PasswordChangeDoneView):
    template_name = 'authentication/email_text/password_change_done.html'

def activate(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = User._default_manager.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        messages.success(
            request, f'Hi {user.username}, your registration was successful!! .')
        return reverse('authentication:login')
    else:
        return reverse_lazy('authentication:email_verification_invalid')


class EmailVerificationConfirm(TemplateView):
    template_name = 'authentication/email_verification_confirm.html'


class EmailVerificationInvalid(TemplateView):
    template_name = 'authentication/email_verification_invalid.html'

authentication/templates/authentication/activate_email.html
{% autoescape off %} Hi {{ user.username }}, Please click on the link to confirm your registration, https://{{ domain }}{% url 'authentication:activate' uidb64=uid token=token %} If you think, it's not you, then just ignore this email. {% endautoescape%}

authentication/templates/authentication/email_verification_invalid.html
{% extends 'base.html' %} {% load i18n %} {% block content %}
<div class="display-sign-container batch-container login-container" style="z-index: 1000;">
    <div class="sign-up-container">
        <div class="sign-up-card">
            <h5>Activation link is invalid!.</h5>
        </div>
    </div>
    <div class="card text-center">
        <div class="card-header">
            Invalid Link
        </div>
        <div class="card-body">
            <h5 class="card-title">Activation link is invalid!.</h5>
            <p class="card-text"><span>Note:</span> Please, kindly go ahead and login.</p>
            <a href="{% url 'authentication:login' %}" class="btn btn-primary">Login</a>
        </div>
    </div>
</div>

{% endblock content %}

authentication/templates/authentication/logged_out.html
{% load i18n %} {% block content %}

<div class="card text-center">
    <div class="card-header">
        You are logged out
    </div>
    <div class="card-body">
        <h5 class="card-title">Logged out!.</h5>
        <p class="card-text"><span>Note:</span> Click here to login again.</p>
        <a href="{% url 'authentication:login' %}" class="btn btn-primary">Login</a>
    </div>
    <div class="card-footer text-muted">
        <a href="/">Home</a>
    </div>
</div>
{% endblock %}

authentication/templates/authentication/login.html
{% load wagtailcore_tags %}{% load static %}{% load wagtailimages_tags %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8"/>
    <title>Login</title>
    <meta content="About" property="og:title"/>
    <meta content="About" property="twitter:title"/>
    <meta content="width=device-width, initial-scale=1" name="viewport"/>
    <meta content="Webflow" name="generator"/>
    
    <link href="https://fonts.gstatic.com" rel="preconnect" crossorigin="anonymous"/>
    <script src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js" type="text/javascript"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="{% static 'css/shop.css' %}" rel="stylesheet" type="text/css"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/landing.css' %}">
    
    <script type="text/javascript">
        WebFont.load({
            google: {
                families: ["Open Sans:300,300italic,400,400italic,600,600italic,700,700italic,800,800italic", "Material Icons:regular", "Material Icons Outlined:regular", "Jost:300,regular,500,600,700,800"]
            }
        });
    </script>
    <script type="text/javascript">
        !function(o, c) {
            var n = c.documentElement
              , t = " w-mod-";
            n.className += t + "js",
            ("ontouchstart"in o || o.DocumentTouch && c instanceof DocumentTouch) && (n.className += t + "touch")
        }(window, document);
    </script>
    <link href="{% static 'images/tabithastore_logo.jpg' %}" rel="shortcut icon" type="image/x-icon"/>
        <link href="{% static 'images/tabithastore_logo.jpg' %}" rel="apple-touch-icon"/>
    
</head>

<body>
    <div class="w-users-userformpagewrap users-page-wrapper">
        <div class="users-form-wrapper">
            <img src="{% if settings.home.SiteLogo.sign_in_image %}{{settings.home.SiteLogo.sign_in_image.url}} {% else %} https://assets-global.website-files.com/65f0219f664a58453bb579a5/65fa679b1c30f8603b92ab00_image.webp {% endif %}" loading="lazy" sizes="(max-width: 767px) 100vw, (max-width: 991px) 360px, 466px" srcset="{% if settings.home.SiteLogo.sign_in_image %}{{settings.home.SiteLogo.sign_in_image.url}} {% else %} https://assets-global.website-files.com/65f0219f664a58453bb579a5/65fa679b1c30f8603b92ab00_image.webp {% endif %} 500w, {% if settings.home.SiteLogo.sign_in_image %}{{settings.home.SiteLogo.sign_in_image.url}} {% else %} https://assets-global.website-files.com/65f0219f664a58453bb579a5/65fa679b1c30f8603b92ab00_image.webp {% endif %} 800w, {% if settings.home.SiteLogo.sign_in_image %}{{settings.home.SiteLogo.sign_in_image.url}} {% else %} https://assets-global.website-files.com/65f0219f664a58453bb579a5/65fa679b1c30f8603b92ab00_image.webp {% endif %} 932w" alt="" class="users-page-image"/>
            <div class="w-users-userloginformwrapper users-form-block">
                {% block messages %} {% if messages %} {% for message in messages %}
                <div class="message-alert">
                    {% if message.level_tag == 'error' %}
                    <div class="alert alert-warning alert-dismissible fade show" role="alert">
                        {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div> {% else %}
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div> {% endif %}


                </div>
                {% endfor %} {% endif %} {% endblock messages %}
                {{login_form.errors}}
                <form class="users-form" action="{% url 'authentication:login' %}" method="post" novalidate>
                    {% csrf_token %}
                    <div class="w-users-userformheader form-header">
                        <h2 class="_30px-title">Log in</h2>
                    </div>
                    {% for field in login_form %}
                    <div class="fieldWrapper">
                        {% if field.errors %}
                        <ul>
                            {% for error in field.errors %}
                            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                                {{error|escape}}
                                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                            </div>
                            {% endfor %}
                        </ul>
                        {% endif %}
                    </div>
                    {% endfor %}
                    <div class="field_card">
                        <label for="id_username" class="users-form-label">Email</label>
                    <input maxlength="255" placeholder="Email" name="username" id="id_username" class="users-input-field w-input input100" type="text" autoComplete="email" required/>
                    </div>
                    <div class="field_card">
                        <label for="id_password" class="users-form-label">Password</label>
                    <input placeholder="Password" name="password" id="id_password" class="users-input-field w-input" type="password" required/>
                    </div>
                    
                    <input type="submit" data-wait="Please wait..." class="w-users-userformbutton users-form-button w-button input100" value="Log In"/>
                    <div class="w-users-userformfooter form-footer">
                        <a href="{% url 'authentication:password_reset' %}">Forgot your Password?</a>
                        <span>
                            Don &#x27;t have an account? <a href="{% url 'authentication:signup' %}" class="secondary-color">Create an account</a>
                        </span>
                    </div>
                </form>
                
                <a href="/" class="back-to-home-link w-inline-block">
                    <div>Back to home</div>
                    <div class="icon">east</div>
                </a>
            </div>
        </div>
    </div>
    <script src="https://d3e54v103j8qbb.cloudfront.net/js/jquery-3.5.1.min.dc5e7f18c8.js?site=65f0219f664a58453bb579a5" type="text/javascript" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js " integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM " crossorigin="anonymous "></script>
    <script src="https://code.jquery.com/jquery-3.5.1.js" 
        integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" 
        crossorigin="anonymous">
    </script> 
    <script src="{% static 'js/webflow.js' %}" type="text/javascript"></script>
</body>

authentication/templates/authentication/pwd_reset_form.html
{% block content %}
<div class="display-sign-container batch-container login-container" style="z-index: 1000;">
    <div class="sign-up-container">
        
        <div class="sign-up-card">
            <div>
                <h2 class="font-weight-bold">Reset Password</h2>
                <p class="forget-password-text">Forgotten your password? Enter your email address below, and
                    we'll
                    email instructions for setting a new one.</p>
            </div>
            <form method="post" action="{% url 'authentication:password_reset' %}">
                {% csrf_token %}
                <div class="form-container">
                    {{ form }}
                </div>
                <input class="sign-up-button" type="submit" value="Reset password" />
            </form>
        </div>
    </div>
</div>
{% endblock content %}

authentication/templates/authentication/thanks.html
{% load wagtailcore_tags %}{% load static %}{% load wagtailimages_tags %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">

</head>

<body>{% block content %}
    <div class="main">
        <div class="bold">
            <div class="tick">
                <div class="boda"></div>
                <div class="sec">
                </div>
            </div>
        </div>
    </div>
    {% endblock %}
</body>

</html>

authentication/templates/authentication/user_update.html
{% load wagtailcore_tags %} {% load static %} {% load wagtailimages_tags %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">{% block title %}
    <title>Account Update</title>{% endblock %}

</head>

<body>
    <div class="body-container">
        {% block content %}
        <div class="main-content">
            <div class="course-main-content">
                <div class="active-course-main-content personal-info-address-container">
                    <form action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label class="form-label" for="id_username">Username:</label>
                            <div class="helptext" id="id_username_helptext">Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</div>
                            <input class="form-control" type="text" name="username" value="{{form.username.value}}" maxlength="150" required aria-describedby="id_username_helptext" id="id_username">
                        </div>
                        <div class="mb-3">
                            <label class="form-label" for="id_first_name">First name:</label>
                            <input class="form-control" type="text" name="first_name" value="{{form.first_name.value}}" maxlength="150" id="id_first_name">
                        </div>
                        <div class="mb-3">
                            <label class="form-label" for="id_last_name">Last name:</label>
                            <input class="form-control" type="text" name="last_name" value="{{form.last_name.value}}" maxlength="150" id="id_last_name">
                        </div>
                        <div class="mb-3">
                            <label class="form-label" for="id_email">Email address:</label>
                            <input class="form-control" type="email" name="email" value="{{form.email.value}}" maxlength="254" id="id_email">
                        </div>
                        <div class="mb-3">
                            <label class="form-label" for="id_country">Country:</label>
                            <input class="form-control" type="text" name="country" value="{{form.country.value}}" maxlength="255" required id="id_country">
                        </div>
                        <div class="mb-3">
                            <label class="form-label" for="id_region">Region:</label>
                            <input class="form-control" type="text" name="region" value="{{form.region.value}}" maxlength="255" required id="id_region">
                        </div>
                        <div class="mb-3">
                            <label class="form-label" for="id_phone_number">Phone number:</label>
                            <input class="form-control" type="text" name="phone_number" value="{{form.phone_number.value}}" maxlength="255" required id="id_phone_number">
                        </div>
                        <div class="mb-3">
                            <label class="form-label" for="id_residential_address">Residential address:</label>
                            <input class="form-control" type="text" name="residential_address" value="{{form.residential_address.value}}" maxlength="255" required id="id_residential_address">
                        </div>
                        <div class="mb-3">
                            <label for="id_avatar">Avatar:</label>
                            <input type="file" class="form-control" name="avatar" accept="image/*" required id="id_avatar">
                        </div>
                        <input class="btn btn-primary" type="submit" value="Update">
                    </form>
                </div>
            </div>
        </div>{% endblock %}
    </div>

</body>

</html>