authentication/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'authentication'

urlpatterns = [
     path(
        route='profile/<int:pk>/',
        view=views.UserDetail.as_view(),
        name='member_profile'
    ),
    path(
        route='update/<int:pk>/',
        view=views.UserUpdateView.as_view(),
        name='user_update'
    ),
    # Login and Password reset
    path(
        route='signup/',
        view=views.UserRegisterView.as_view(),
        name='signup'
    ),
    path(route='signup/successful', view=views.SignUpSuccessful.as_view(), name='signup_successful'),
    path(
        route='login/',
        view=views.UserLoginView.as_view(),
        name='login'
    ),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    path(
        route='reset-password',
        view=views.PasswordResetView.as_view(),
        name='password_reset'
    ),
    path('password-reset/done/', views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/',
         views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset_complete/done/', views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
    path('password-change', views.PasswordChangeView.as_view(),
         name='password_change'),
    path('password-change/done/', views.PasswordChangeDoneView.as_view(),
         name='password_change_done'),
     path('email/verification/confirm', views.EmailVerificationConfirm.as_view(),
         name='email_verification_confirm'),
     path('email/verification/invalid', views.EmailVerificationInvalid.as_view(),
         name='email_verification_invalid'),
    path('activate/<uidb64>/<token>/',
         views.activate, name='activate'),

]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.ShopView.as_view(), name='home'),
    path('shop/<str:slug>/', views.CategoryProductView.as_view(), name='category'),
    path('check-out/', views.CheckOut.as_view() , name='checkout'),
    path('user-account/', views.UserAccountView.as_view() , name='account'),

    path('config/', views.stripe_config),
    path('success/', views.SuccessView.as_view()),
    path('cancel/', views.CancelledView.as_view()),
    path(
        route='search_results',
        view=views.SearchResultsList.as_view(),
        name='search_results'
    ),
]

authentication/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractUser
from wagtail.snippets.models import register_snippet
from wagtail.admin.panels import FieldPanel, InlinePanel, FieldRowPanel, MultiFieldPanel, PageChooserPanel
from django.utils.translation import gettext_lazy as _
from django.utils.text import slugify
from django.urls import reverse
from cloudinary.models import CloudinaryField
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser, PermissionsMixin

class MyUserManager(BaseUserManager):
    def create_user(self, email, password=None):
        """
        Creates and saves a User with the given email and password.
        """
        if not email:
            raise ValueError("Users must have an email address")

        user = self.model(
            email=self.normalize_email(email),
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(
            email,
            password=password,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user
class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(verbose_name='email', max_length=255, unique=True)
    first_name = models.CharField(verbose_name='First Name', max_length=255, null=True, blank=True)
    last_name = models.CharField(verbose_name='Last Name', max_length=255, null=True, blank=True)
    date_joined = models.DateTimeField(verbose_name='date joined', auto_now_add=True, null=True)
    last_login = models.DateTimeField(verbose_name='last login', auto_now=True, null=True)
    country = models.CharField(verbose_name='country', max_length=255, null=True, blank=True)
    region = models.CharField(verbose_name='region', max_length=255, null=True, blank=True)
    city = models.CharField(verbose_name='country', max_length=255, null=True, blank=True)
    phone_number = models.CharField(max_length=255, null=True, blank=True)
    residential_address = models.CharField(max_length=255, null=True, blank=True)
    avatar = CloudinaryField("image", null=True, blank=True)

    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    # is_staff = models.BooleanField(default=False)

    objects = MyUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def get_absolute_url(self):
        return reverse('shop:account')
    
    @property
    def full_name(self):
        return f'{self.first_name} {self.last_name}'

    def __str__(self):
        return f'{self.email} - {self.full_name}'

authentication/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from wagtail.users.forms import UserEditForm, UserCreationForm

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.utils.translation import gettext_lazy as _
# from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import (
    AuthenticationForm,
)
from authentication.models import User


class UserSignInForm(AuthenticationForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder': 'Email'}), label='Email')
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Password..'}), label='Password')

    class Meta:
        model = User
        fields = ['email', 'password']
class UserRegisterForm(UserCreationForm):
    """
        Creates User registration form for signing up.
    """
    def __init__(self, *args, **kwargs):
        super(UserRegisterForm, self).__init__(*args, **kwargs)
        # self.fields['username'].widget.attrs.pop("autofocus", None)

    email = forms.EmailField(max_length=254, required=True, widget=forms.EmailInput(attrs={
        "name": "email", "class": "input100",
        "placeholder": "Email"
    }
    ),
        help_text='Required. Input a valid email address.'
    )
    password1 = forms.CharField(label="Password",
    widget=forms.PasswordInput(attrs={
        "name": "password", "class": "input100",
        "placeholder": "Password"
    }
    ),
    )

    password2 = forms.CharField(label="Confirm Password",
                                help_text=_(
                                    "Enter the same password as before, for verification."),
    widget=forms.PasswordInput(attrs={"name": "Confirm Password", "class": "input100", "placeholder": "Confirm Password"}),
    )

    class Meta:
        model = User
        fields = ['email', 'password1', 'password2']
        # widgets = {

        #     "username": forms.TextInput(attrs={
        #         "name": "username", "class": "input100",
        #         "placeholder": "Username"
        #     }),
        # }

    def save(self, commit=True):
        user = super(UserRegisterForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user
    
class CustomUserEditForm(UserEditForm):
    email = forms.CharField(required=False, label=_("Email"))
    country = forms.CharField(required=False, label=_("Country"))
    region = forms.CharField(required=False, label=_("State"))
    city = forms.CharField(required=False, label=_("City"))
    phone_number = forms.CharField(required=False, label=_("Phone number"))
    residential_address = forms.CharField(required=False, label=_("Residential address"))
    avatar = forms.ImageField(required=False, label=_("Avatar"))


class CustomUserCreationForm(UserCreationForm):
    email = forms.CharField(required=False, label=_("Email"))
    country = forms.CharField(required=False, label=_("Country"))
    region = forms.CharField(required=False, label=_("State"))
    city = forms.CharField(required=False, label=_("City"))
    phone_number = forms.CharField(required=False, label=_("Phone number"))
    residential_address = forms.CharField(required=False, label=_("Residential address"))
    avatar = forms.ImageField(required=False, label=_("Avatar"))

authentication/views.py
from django.shortcuts import render
from django.contrib.auth.forms import (
    AuthenticationForm,
)
from django.urls import reverse_lazy
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import TemplateView, DetailView
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic import View
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.contrib.auth.tokens import default_token_generator
from django.utils.http import urlsafe_base64_decode
from django.urls import reverse_lazy, reverse
from django.contrib.auth import get_user_model
User = get_user_model()
from django.contrib.auth.views import (PasswordResetDoneView, PasswordResetConfirmView,
                                        PasswordResetCompleteView, PasswordChangeView,
                                       PasswordChangeDoneView, PasswordResetView)
from .models import User as Member
from django.http.response import HttpResponseRedirect
from django.core.mail import EmailMessage
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes
from django.contrib.sites.shortcuts import get_current_site
from .forms import UserRegisterForm
from django.contrib.auth.mixins import LoginRequiredMixin
from authentication.forms import UserSignInForm
from wagtail.admin.forms.auth import LoginForm
# Create your views here.

class SignUpSuccessful(TemplateView):
    template_name = 'authentication/thanks.html'
class UserDetail(LoginRequiredMixin, DetailView):
    model = Member
    template_name = 'courses/profile_detail.html'
    login_url = "authentication:login"
    redirect_field_name = "redirect_to"

class UserUpdateView(LoginRequiredMixin, UpdateView):
    fields = ['first_name', 'last_name', 'email', 'country', 'region', 'city', 'phone_number', 'residential_address', 'avatar']
    model = Member
    template_name = 'authentication/user_update.html'
    login_url = "authentication:login"
    redirect_field_name = "redirect_to"
class UserLoginView(View):
    """
     Logs author into dashboard.
    """
    template_name = 'authentication/login.html'
    context_object = {"login_form": LoginForm}

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, self.context_object)

    def post(self, request, *args, **kwargs):

        login_form = LoginForm(data = request.POST)

        if login_form.is_valid():
            email = login_form.cleaned_data['username']
            password = login_form.cleaned_data['password']
            user = authenticate(request, email=email, password=password)

            
            login(request, user)
            messages.success(request, f"Login Successful ! "
                                f"Welcome {user.email}.")
            
            return redirect('shop:home')

        else:
            messages.error(request,
                           f"Please enter a correct email and password. Note that both fields may be case-sensitive."
                           )
            return render(request, self.template_name, self.context_object)

class UserRegisterView(View):
    """
      View to let users register
    """
    template_name = 'authentication/register.html'
    context = {
        "register_form": UserRegisterForm()
    }

    def get(self, request):
        success_message = "Successful"

        self.context['success_message'] = success_message
        return render(request, self.template_name, self.context)

    def post(self, request, *args, **kwargs):

        register_form = UserRegisterForm(request.POST)

        if register_form.is_valid():
            user = register_form.save(commit=False)
            user.is_active = True
            user.is_staff = True
            user.save()
            current_site = get_current_site(request)
            mail_subject = 'Activate your account.'
            message = render_to_string('authentication/activate_email.html'
                                       , {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': default_token_generator.make_token(user),
                'protocol': 'https',
            }
            )
            from_email = 'tabitha.market@gmail.com'
            to_email = register_form.cleaned_data.get('email')
            email = EmailMessage(
                mail_subject, message, from_email, to=[to_email]
            )
            email.send()

            return HttpResponseRedirect(reverse_lazy('authentication:email_verification_confirm'))

        else:
            messages.error(request, "Please provide valid information.")
            # Redirect user to register page
            return render(request, self.template_name, self.context)

    # def get_success_url(self):
    #     return reverse('authentication:signup_successful')


class PasswordResetView(PasswordResetView):
    template_name = 'authentication/pwd_reset_form.html'
    email_template_name = "authentication/email_text/password_reset_email.html"
    from_email = ''
    subject_template_name = "authentication/email_text/password_reset_subject.txt"
    success_url = reverse_lazy("authentication:password_reset_done")

class PasswordResetDoneView(PasswordResetDoneView):
    template_name = 'authentication/email_text/password_reset_done.html' 

class PasswordResetConfirmView(PasswordResetConfirmView):
    template_name = 'authentication/email_text/password_reset_confirm.html'
    success_url = reverse_lazy("authentication:password_reset_complete")

class PasswordResetCompleteView(PasswordResetCompleteView):
    template_name = 'authentication/email_text/password_reset_complete.html'

class PasswordChangeView(PasswordChangeView):
    template_name = 'authentication/email_text/password_change_form.html'
    success_url = reverse_lazy("authentication:password_change_done")

class PasswordChangeDoneView(PasswordChangeDoneView):
    template_name = 'authentication/email_text/password_change_done.html'

def activate(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = User._default_manager.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        messages.success(
            request, f'Hi {user.username}, your registration was successful!! .')
        return reverse('authentication:login')
    else:
        return reverse_lazy('authentication:email_verification_invalid')


class EmailVerificationConfirm(TemplateView):
    template_name = 'authentication/email_verification_confirm.html'


class EmailVerificationInvalid(TemplateView):
    template_name = 'authentication/email_verification_invalid.html'

authentication/templates/authentication/email_text/password_change_done.html
 {% extends 'base.html' %} {% block content %}
<p>You have successfully changed your password</p>

<a href="{% url 'authentication:login' %}"></a>
{% endblock %}

authentication/templates/authentication/email_text/password_change_form.html
{% extends 'base.html' %} {% load i18n %} {% block content %}

<div class="display-sign-container batch-container login-container" style="z-index: 1000;">
    <div class="sign-up-container">
        <div class="sign-up-card">
            <h2 class="font-weight-bold">Enter New Password</h2>
            <p>Kindly enter a new password.</p>

            <form action="" method="post">
                {% csrf_token %}
                <div class="form-container">
                    {{ form }}
                </div>
                <input type="submit" class="sign-up-button" value="Submit">
            </form>
        </div>
    </div>
</div>
{% endblock %}

authentication/templates/authentication/email_text/password_reset_complete.html
{% extends 'base.html' %} {% block content %}
<div class="display-sign-container batch-container login-container" style="z-index: 1000;">
    <div class="sign-up-container">
        <div class="sign-up-card">
            <h1>The password has been changed!</h1>
            <p><a class="text-info" href="{% url 'authentication:login' %}">log in again?</a></p>
        </div>
    </div>
</div>
{% endblock content %}

authentication/templates/authentication/email_text/password_reset_confirm.html
{% extends 'base.html' %} {% block content %}
<div class="display-sign-container batch-container login-container" style="z-index: 1000;">
    <div class="sign-up-container">
        <div class="sign-up-card">
            {% if validlink %}
            <p>Please enter (and confirm) your new password.</p>
            <form action="" method="post">
                {% csrf_token %}
                <table>
                    <tr>
                        <td>{{ form.new_password1.errors }}
                            <label for="id_new_password1">New password:</label>
                        </td>
                        <td>{{ form.new_password1 }}</td>
                    </tr>
                    <tr>
                        <td>{{ form.new_password2.errors }}
                            <label for="id_new_password2">Confirm password:</label>
                        </td>
                        <td>{{ form.new_password2 }}</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td><input type="submit" value="Change my password" /></td>
                    </tr>
                </table>
            </form>
            {% else %}
            <h2>Password reset failed</h2>
            <p>The password reset link was invalid, possibly because it has already been used. Please request a new password reset.
            </p>
            {% endif %}
        </div>
    </div>
</div>
{% endblock content %}

authentication/templates/authentication/email_text/password_reset_done.html
{% extends 'base.html' %} {% load i18n %} {% block content %}
<div class="display-sign-container batch-container login-container" style="z-index: 1000;">
    <div class="sign-up-container">

        <div class="sign-up-card">
            <h5>We've emailed you instructions for setting your password. If they haven't arrived in a few minutes, check your spam folder.
            </h5>
        </div>
    </div>
</div>

{% endblock content %}

authentication/templates/authentication/email_text/password_reset_email.html
 Hello {{user.username}}, We received a request to reset the password for your account for {{email}}. To initiate the password reset process for your account, click the link below. {{ protocol }}://{{ domain }}{% url 'authentication:password_reset_confirm'
uidb64=uid token=token %} This link can only be used once. If you need to reset your password again, please visit {{ protocol }}://{{domain}} and request another reset. If you did not make this request, you can simply ignore this email. Sincerely, DLBC
Clarksville