authentication/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'authentication'

urlpatterns = [
     path(
        route='profile/<int:pk>/',
        view=views.UserDetail.as_view(),
        name='member_profile'
    ),
    path(
        route='update/<int:pk>/',
        view=views.UserUpdateView.as_view(),
        name='user_update'
    ),
    # Login and Password reset
    path(
        route='signup/',
        view=views.UserRegisterView.as_view(),
        name='signup'
    ),
    path(route='signup/successful', view=views.SignUpSuccessful.as_view(), name='signup_successful'),
    path(
        route='login/',
        view=views.UserLoginView.as_view(),
        name='login'
    ),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    path(
        route='reset-password',
        view=views.PasswordResetView.as_view(),
        name='password_reset'
    ),
    path('password-reset/done/', views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/',
         views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset_complete/done/', views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
    path('password-change', views.PasswordChangeView.as_view(),
         name='password_change'),
    path('password-change/done/', views.PasswordChangeDoneView.as_view(),
         name='password_change_done'),
     path('email/verification/confirm', views.EmailVerificationConfirm.as_view(),
         name='email_verification_confirm'),
     path('email/verification/invalid', views.EmailVerificationInvalid.as_view(),
         name='email_verification_invalid'),
    path('activate/<uidb64>/<token>/',
         views.activate, name='activate'),

]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.ShopView.as_view(), name='home'),
    path('shop/<str:slug>/', views.CategoryProductView.as_view(), name='category'),
    path('check-out/', views.CheckOut.as_view() , name='checkout'),
    path('user-account/', views.UserAccountView.as_view() , name='account'),

    path('config/', views.stripe_config),
    path('success/', views.SuccessView.as_view()),
    path('cancel/', views.CancelledView.as_view()),
    path(
        route='search_results',
        view=views.SearchResultsList.as_view(),
        name='search_results'
    ),
]

home/models.py
from django.db import models
from wagtail.fields import RichTextField
from wagtail.models import Page
from django.shortcuts import render
from wagtail.contrib.settings.models import BaseSiteSetting, register_setting
from wagtail.admin.panels import FieldPanel, InlinePanel, FieldRowPanel, MultiFieldPanel, PageChooserPanel
from wagtail.contrib.forms.models import AbstractEmailForm, AbstractFormField
from wagtail.snippets.models import register_snippet
from modelcluster.fields import ParentalKey
from wagtail.contrib.forms.panels import FormSubmissionsPanel
from cloudinary.models import CloudinaryField
from shop.models import Category, Cart, ProductPage, CartItem
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.contrib import messages


class HomePage(Page):
    template = 'shop/shop.html'
    max_count = 1

    content_panels = Page.content_panels + [
        # FieldPanel('hero_section_title'),
    ]

    def get_context(self, request, *args, **kwargs):
        context = super(HomePage, self).get_context(request, *args, **kwargs)

        # context["daily_devotions"] = daily_devotions
        return context


class SubscribeFormField(AbstractFormField):
    page = ParentalKey('SubscribeFormPage', on_delete=models.CASCADE, related_name='form_fields')

class SubscribeFormPage(AbstractEmailForm):
    template = 'home/subscribe_form.html'
    intro = RichTextField(blank=True)
    thank_you_text = RichTextField(blank=True)
    content_panels = AbstractEmailForm.content_panels + [
        FormSubmissionsPanel(),
        FieldPanel('intro'),
        InlinePanel('form_fields', label="Form fields"),
        FieldPanel('thank_you_text'),
        MultiFieldPanel([
            FieldRowPanel([
                FieldPanel('from_address', classname="col6"),
                FieldPanel('to_address', classname="col6"),
            ]),
            FieldPanel('subject'),
        ], "Email"),
    ]

    def get_context(self, request, *args, **kwargs):
        context = super(SubscribeFormPage, self).get_context(request, *args, **kwargs)

        categories = Category.objects.all()
        if request.user.is_authenticated:
            cart = Cart.objects.get_or_create(user=request.user)[0]
            cart_items = cart.cartitem_set.all()
            context['cart_items'] = cart_items
            context['cart'] = cart
        else:
            cart = None
        context['categories'] = categories
        return context

    def serve(self, request, *args, **kwargs):
        if request.method == 'POST':
            form = self.get_form(request.POST, page=self, user=request.user)
            action = request.POST.get('action')
            cart, _ = Cart.objects.get_or_create(user=request.user)
            if form.is_valid():
                if action == 'update':
                    product_id = int(request.POST.get('cart_product'))
                    product = get_object_or_404(ProductPage, pk=product_id)
                    cart_item = get_object_or_404(CartItem, cart=cart, product=product)
                    new_quantity = int(request.POST.get('cart_quantity', 0))
                    if new_quantity <= 0:
                        cart_item.delete()
                    else:
                        cart_item.quantity = new_quantity
                        cart_item.save()
                    messages.success(request, f"Cart update successful !!")
                    return redirect('shop:checkout')
                
                self.process_form_submission(form)
                # Update the original landing page context with other data
                landing_page_context = self.get_context(request)
                landing_page_context['email'] = form.cleaned_data['email']

                return render(
                    request,
                    self.get_landing_page_template(request),
                    landing_page_context
                )
        else:
            form = self.get_form(page=self, user=request.user)

        context = self.get_context(request)
        context['form'] = form
        return render(
            request,
            self.get_template(request),
            context
        )

@register_setting
class SubscribeFormSettings(BaseSiteSetting):
    subscribe_form_page = models.ForeignKey(
        'wagtailcore.Page', null=True, on_delete=models.SET_NULL)

    panels = [
        # note the page type declared within the pagechooserpanel
        PageChooserPanel('subscribe_form_page', ['home.SubscribeFormPage']),
    ]

@register_snippet
class OurValues(models.Model):
    value_title = models.CharField(max_length=500, null=True, blank=True)
    value_text = RichTextField(null=True, blank=True)
    value_image = CloudinaryField("image", null=True, blank=True, help_text="upload image")

    panels = [
        FieldPanel('value_title'),
        FieldPanel('value_text'),
        FieldPanel('value_image'),
    ]
    def __str__(self):
        return self.value_title
    
    class Meta:
        verbose_name_plural = "Our Values"

@register_snippet
class TrustedBy(models.Model):
    organization_name = models.CharField(max_length=500, null=True, blank=True)
    logo = CloudinaryField("image", null=True, blank=True, help_text="upload logo of trusted-by companies/businesses")

    panels = [
        FieldPanel('organization_name'),
        FieldPanel('logo'),
    ]
    def __str__(self):
        return self.organization_name
    
    class Meta:
        verbose_name_plural = "Trusted By Businesses"

@register_snippet
class Team(models.Model):
    full_name = models.CharField(max_length=500, null=True, blank=True)
    position = models.URLField(null=True, blank=True)
    photo = CloudinaryField("image", null=True, blank=True, help_text="upload photo")
    facebook = models.URLField(null=True, blank=True)
    twitter = models.URLField(null=True, blank=True)
    instagram = models.URLField(null=True, blank=True)
    linkedin = models.URLField(null=True, blank=True)
    whatsapp = models.URLField(null=True, blank=True)

    panels = [
        FieldPanel('full_name'),
        FieldPanel('position'),
        FieldPanel('photo'),
        FieldPanel('facebook'),
        FieldPanel('twitter'),
        FieldPanel('instagram'),
        FieldPanel('linkedin'),
        FieldPanel('whatsapp'),
    ]
    def __str__(self):
        return self.full_name
    
    class Meta:
        verbose_name_plural = "Teams"

    
class About(Page):
    max_count = 1
    template = 'home/about.html'
    welcome_to_tabitha_title = models.CharField(max_length=1000, null=True, blank=True)
    welcome_to_tabitha_text = RichTextField(null=True, blank=True)
    our_mission_title = models.CharField(max_length=1000, null=True, blank=True)
    our_mission_text = RichTextField(null=True, blank=True)
    our_mission_image = CloudinaryField("image", null=True, blank=True, help_text="upload image for Mission section")
    our_story_title = models.CharField(max_length=1000, null=True, blank=True)
    our_story_text = RichTextField(null=True, blank=True)
    our_story_image1 = CloudinaryField("image", null=True, blank=True, help_text="upload first for Story section")
    our_story_image2 = CloudinaryField("image", null=True, blank=True, help_text="upload second for Story section")

    content_panels = Page.content_panels + [
        FieldPanel('welcome_to_tabitha_title'),
        FieldPanel('welcome_to_tabitha_text'),
        FieldPanel('our_mission_title'),
        FieldPanel('our_mission_text'),
        FieldPanel('our_mission_image'),
        FieldPanel('our_story_title'),
        FieldPanel('our_story_text'),
        FieldPanel('our_story_image1'),
        FieldPanel('our_story_image2'),
    ]

    def get_context(self, request, *args, **kwargs):
        context = super(About, self).get_context(request, *args, **kwargs)

        categories = Category.objects.all()
        if request.user.is_authenticated:
            cart = Cart.objects.get_or_create(user=request.user)[0]
            cart_items = cart.cartitem_set.all()
            context['cart_items'] = cart_items
            context['cart'] = cart
        else:
            cart = None

        values = OurValues.objects.all()
        teams = Team.objects.all()
        trusted_by_companies = TrustedBy.objects.all()
        context['categories'] = categories
        context['values'] = values
        context['teams'] = teams
        context['trusted_by_companies'] = trusted_by_companies
        return context
    
    def serve(self, request):
        if request.method == 'POST':
            action = request.POST.get('action')
            cart, _ = Cart.objects.get_or_create(user=request.user)
            
            if action == 'update':
                product_id = int(request.POST.get('cart_product'))
                product = get_object_or_404(ProductPage, pk=product_id)
                cart_item = get_object_or_404(CartItem, cart=cart, product=product)
                new_quantity = int(request.POST.get('cart_quantity', 0))
                if new_quantity <= 0:
                    cart_item.delete()
                else:
                    cart_item.quantity = new_quantity
                    cart_item.save()
                messages.success(request, f"Cart update successful !!")
                return redirect('shop:checkout')
            return HttpResponseRedirect(reverse('shop:checkout'))
        else:
            return render(
            request,
            self.get_template(request),
            self.get_context(request)
        )

    
class PrivacyPolicy(Page):
    max_count = 1
    template = 'home/privacy-policy.html'
    privacy_policy = RichTextField(null=True, blank=True)
    refund_policy = RichTextField(null=True, blank=True)
    term_and_use = RichTextField(null=True, blank=True)

    content_panels = Page.content_panels + [
        FieldPanel('privacy_policy'),

search/views.py
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.template.response import TemplateResponse

from wagtail.models import Page

# To enable logging of search queries for use with the "Promoted search results" module
# <https://docs.wagtail.org/en/stable/reference/contrib/searchpromotions.html>
# uncomment the following line and the lines indicated in the search function
# (after adding wagtail.contrib.search_promotions to INSTALLED_APPS):

# from wagtail.contrib.search_promotions.models import Query


def search(request):
    search_query = request.GET.get("query", None)
    page = request.GET.get("page", 1)

    # Search
    if search_query:
        search_results = Page.objects.live().search(search_query)

        # To log this query for use with the "Promoted search results" module:

        # query = Query.get(search_query)
        # query.add_hit()

    else:
        search_results = Page.objects.none()

    # Pagination
    paginator = Paginator(search_results, 10)
    try:
        search_results = paginator.page(page)
    except PageNotAnInteger:
        search_results = paginator.page(1)
    except EmptyPage:
        search_results = paginator.page(paginator.num_pages)

    return TemplateResponse(
        request,
        "search/search.html",
        {
            "search_query": search_query,
            "search_results": search_results,
        },
    )

home/templates/home/components/footer.html
{% load wagtailcore_tags %}{% load static %}{% load wagtailimages_tags %}
<footer id="footer" class="footer">
    <div class="container">
        <div class="newsletter-block">
            <div class="w-layout-vflex _10px-gap">
                <div class="_30px-title">Subscribe our newsletter</div>
                <p class="paragraph-300">
                    Subscribe to our newsletter for exclusive updates, promotions,<br/>and exciting news delivered straight to your inbox!
                </p>
            </div>
            <div class="subscription-form-block w-form">
                {% include 'home/subscribe_form.html' %}
            </div>
        </div>
    </div>
    <div class="main-footer">
        <div class="container">
            <div class="footer-wrapper">
                <div class="footer-block first-block">
                    <a href="/" class="navbar-logo-wrapper w-nav-brand">
                        <img src="{% static 'images/tabithastore_logo.jpg' %}" loading="lazy" width="70" alt="" class="site-logo"/>
                    </a>
                    <p class="footer-paragraph">At Tabitha, we curate diverse, quality products ensuring a stress-free shopping experience. Our dedicated team provides prompt support. Join our community.</p>
                    <div class="social-share-icon-container">
                        {% if settings.home.SiteSocial.facebook %}
                        <a href="{{settings.home.SiteSocial.facebook}}" target="_blank" class="footer-social-icon"></a>
                        {% endif %}
                        {% if settings.home.SiteSocial.instagram %}
                        <a href="{{settings.home.SiteSocial.instagram}}" target="_blank" class="footer-social-icon"></a>
                        {% endif %}
                        {% if settings.home.SiteSocial.twitter %}
                        <a href="{{settings.home.SiteSocial.twitter}}" target="_blank" class="footer-social-icon"></a>
                        {% endif %}
                        {% if settings.home.SiteSocial.youtube %}
                        <a href="{{settings.home.SiteSocial.youtube}}" target="_blank" class="footer-social-icon"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" style="fill: #8f9eb2;transform: ;msFilter:;"><path d="M21.593 7.203a2.506 2.506 0 0 0-1.762-1.766C18.265 5.007 12 5 12 5s-6.264-.007-7.831.404a2.56 2.56 0 0 0-1.766 1.778c-.413 1.566-.417 4.814-.417 4.814s-.004 3.264.406 4.814c.23.857.905 1.534 1.763 1.765 1.582.43 7.83.437 7.83.437s6.265.007 7.831-.403a2.515 2.515 0 0 0 1.767-1.763c.414-1.565.417-4.812.417-4.812s.02-3.265-.407-4.831zM9.996 15.005l.005-6 5.207 3.005-5.212 2.995z"></path></svg></a>
                        {% endif %}
                    </div>
                </div>
                <div class="footer-block">
                    <div class="footer-title">Useful Links</div>
                    <div class="list-block">
                        <a href="/" class="footer-link w-inline-block">
                            <div class="footer-link-icon">chevron_right</div>
                            <div>Home</div>
                        </a>
                        <a href="{{ settings.home.ImportantPages.page_url.about }}" class="footer-link w-inline-block">
                            <div class="footer-link-icon">chevron_right</div>
                            <div>About</div>
                        </a>
                        <a href="{{ settings.home.ImportantPages.page_url.contact }}" class="footer-link w-inline-block">
                            <div class="footer-link-icon">chevron_right</div>
                            <div>Contact</div>
                        </a>
                    </div>
                </div>
                <div class="footer-block">
                    <div class="footer-title">Quick Links</div>
                    <div class="list-block">
                        
                        <a href="{% url 'shop:account' %}" aria-current="page" class="footer-link w-inline-block w--current">
                            <div class="footer-link-icon">chevron_right</div>
                            <div>Account</div>
                        </a>
                        <a href="{% url 'authentication:login' %}" class="footer-link w-inline-block">
                            <div class="footer-link-icon">chevron_right</div>
                            <div>Log In</div>
                        </a>
                        <a href="{% url 'authentication:signup' %}" class="footer-link w-inline-block">
                            <div class="footer-link-icon">chevron_right</div>
                            <div>Sign Up</div>
                        </a>
                        <a href="{{ settings.home.ImportantPages.page_url.privacy }}" class="footer-link w-inline-block">
                            <div class="footer-link-icon">chevron_right</div>
                            <div>Privacy policy</div>
                        </a>
                    </div>
                </div>
                <div class="footer-menu-links-wrapper"></div>
                <div class="footer-block subscribe-block">
                    <div class="footer-title">Contact Address</div>
                    <address class="footer-paragraph">
                        {{ settings.home.SiteContact.address }}
                    </address>
                    <div class="w-layout-vflex _10px-gap">
                        <div class="footer-title">Contact Address</div>
                        <div class="horizontal-block-10px-gap">
                            <img src="https://assets-global.website-files.com/65f0219f664a58453bb579a5/65f13c13f60edff8333303ba_phone-call%201.svg" loading="lazy" alt="" class="_16px-svg"/>
                            <div class="paragraph-300"><a href="tel:+{{ settings.home.SiteContact.phone2 }}">{{ settings.home.SiteContact.phone2 }}</a></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="footer-bottom">
        <div class="container middle-allign">
            <div class="footer-copyright">
                Copyright © <span id="year">2024 </span> CityXplorer LLC
            </div>
        </div>
    </div>
</footer>

home/templates/home/components/left-sidebar.html
<div data-w-id="cc6e4718-ba15-402c-9595-d69fba7a0cda" class="hide-filter-bar">
    <div class="icon">filter_alt_off</div>
    <div>Hide Filter</div>
</div>
<div class="sidebar-form">
    <div class="sidebar-wrapper">
        <form action="{% url 'shop:search_results' %}" class="search w-form">
            <input class="sidebar-search-input w-input" maxlength="256" name="search" placeholder="Search…" type="search" id="search" required=""/>
            <input type="submit" class="sidebar-search-button w-button" value="search"/>
        </form>
        <div class="w-layout-vflex _10px-gap">
            <div class="_20px-bold-title">Show all categories</div>
            <div class="full-width">
                <div class="widget">
                    <div class="checkbox-field">
                        <a href="/" aria-current="page" class="checkbox w-inline-block w--current"></a>
                        <div class="paragraph-300">All</div>
                    </div>
                    <div class="w-dyn-list">
                        <div role="list" class="product-categories w-dyn-items">
                            {% if categories %}
                            {% for cat in categories %}
                            <div role="listitem" class="w-dyn-item">
                                <div class="checkbox-field">
                                    <a href="{% url 'shop:category' cat.slug %}" class="checkbox w-inline-block" onclick="setCurrent(this)"></a>
                                    <div class="paragraph-300">{{cat.category_name|title}}</div>
                                </div>
                            </div>
                            {% endfor %}
                            {% endif %}
                            <script>
                                function setCurrent(ele) {
                                    ele.setAttribute('aria-current', 'page')
                                }
                            </script>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- <div class="w-layout-vflex _10px-gap">
            <div class="_20px-bold-title">Widget Price Filter</div>
            <div class="full-width w-dyn-list">
                <div role="list" class="widget w-dyn-items">
                    <div role="listitem" class="w-dyn-item">
                        <div class="checkbox-field">
                            <a href="/price-range/1---100" class="checkbox w-inline-block"></a>
                            <div class="paragraph-300">$1 - $100</div>
                        </div>
                    </div>
                    <div role="listitem" class="w-dyn-item">
                        <div class="checkbox-field">
                            <a href="/price-range/101---200" class="checkbox w-inline-block"></a>
                            <div class="paragraph-300">$101 - $200</div>
                        </div>
                    </div>
                    <div role="listitem" class="w-dyn-item">
                        <div class="checkbox-field">
                            <a href="/price-range/201---300" class="checkbox w-inline-block"></a>
                            <div class="paragraph-300">$201 - $300</div>
                        </div>
                    </div>
                </div>
            </div>
        </div> -->
    </div>
</div>

home/templates/home/components/search.html
<form action="{% url 'shop:search_results' %}" method="get" class="search-bar-wrapper w-form">
    <input class="search-bar w-input" maxlength="256" name="search" placeholder="Search by product, price, category and key words" type="search" id="search" required=""/>
    <input type="submit" class="search-button w-button" value="search"/>
</form>